### PR TITLE
Change _plogpdf function to accept four arguments

### PR DESCRIPTION
**Pull request by ismailsenoz**

### CODE REVIEW

**Comment by bvdmitri** [comment]
Could you please provide a description for the PR? At first glance, it’s not clear why this change is necessary. Additionally, please include tests that were failing before this change and are passing afterward. Thanks!

**Comment by ismailsenoz** [comment]
This is needed because many of the projections that are failing are due to presence of factorial, gamma, beta etc. type of functions in the log-partition and base measure. Because these functions are numerically challenging tests in ExponentialFamilyProjections either fail or display strange behavior such as extra factor of 2 when projecting into Chisq. I noticed a strange behavior when writing tests for projecting into Poisson.  When the lambda parameter of Poisson is large, due to presence of factorial in the basemeasure, projection is wrong. When the projection is done with unnormalized density these problems are solved. Therefore, the test suit in ExponentialFamilyProjection needs to be implemented with _plogpdf removing all the basemeasure and log-partition factors. In the current implementation of _plogpdf only logpartition is excluded. By excluding basemeasure we can correctly project into Chisq and Poisson. This why it is needed to include the 4th argument.

**Comment by Nimrais** [comment]
@ismailsenoz @bvdmitri I will add a small test for this functionality

**Comment by ismailsenoz** [comment]
AFAIK none of the tests in ExponentialFamily were failing and there is no explicit tests for _plogpdf functions beforehand anyways. This function was implicitly tested with all logpdf and pdf calls.

**Comment by Nimrais** [comment]
Yeah, you are right, but if are supposed to use it somewhere, this interface from a hidden optimisation for big containers becomes functionality.

_plogpdf was initially added just to faster compute logpdf for big containers.

**Comment by Nimrais** [comment]
It's assisting from the perspective of the target function.

If you try to project x -> logpdf(Poisson, x) where the Poisson distribution has a very large natural parameter, the projection fails to recover the correct value. The base measure has factorial in its computations, and small and large natural parameters become indistinguishable.

However, if you project x -> log(x) * η, it works fine and correctly recovers the η parameter.
The proposal is to use unnormalized densities as the target function inside projection procedures for tests to make them more stable, at least for the distributions where to compute logpdf is numerically problematic such as Chisq, Poisson, Gamma.

**Comment by Nimrais** [comment]
> Perhaps you refer to the `logpdf` which is used in the tests inside the `f` function, but it’s important to note that in general the function `f`, which is passed to the `project_to` method, is arbitrary, and we cannot manipulate or adjust what it does internally.

Yes, we unfortunately can not manipulate what user provide us, but we can decide what we are testing. And @ismailsenoz is that is not much of test for Poisson or Chisq to project them trough their logpdf, it just gives unreasonable values.

**Comment by bvdmitri** [comment]
> The proposal is to use unnormalized densities as the target function inside projection procedures for tests to make them more stable

I understand the proposal for the tests, but how would you practically implement this during actual inference? In practice, `f` is arbitrary and can perform various operations internally, such as calling `logpdf` for a Poisson distribution. Since we cannot manipulate `f`, this doesn’t seem like a real solution for practical scenarios, even if it makes tests pass.

> it does not make much of a sense to test for Poisson or Chisq to project them trough their logpdf, it just gives unreasonable values.

But this is precisely what will happen during real inference.

> but we can decide what we are testing

True, but we shouldn’t simplify our tests just to ensure they pass. There are many ways to set up tests—for example, adjusting `stepsize` to a small value and increasing the number of iterations to an unreasonable large value, or even using BigFloat for better stability. In my opinion, tests should reflect real-world conditions closely and not just aim to pass.

If tests for `Poisson` only pass when we use a very specific usage of `_plogpdf`, but we cannot realistically ensure this in any practical scenario, then the computation is fundamentally flawed. A passing test would only create a false sense of stability.

**Comment by ismailsenoz** [comment]
The problem of the test suit is it is trying to check whether the projection gets finer with increasing number of samples and iterations. In order to test this property properly we need to ensure that the projection is correct. 

In practice we can not control what kind of function is passed. But in practice no one is going to try projecting normal into normal or poisson into poisson as well. So the fact that some of projection tests passing doesn't mean they are useful neither. If someone tries to project unnormalized density involving factorials or gamma it is a problem but that is not the case often.

**Comment by bvdmitri** [comment]
Extra thought, we actually use ‘logpartition’ term in the projection step, which is presumably unstable for certain distributions, but if we remove it *only* from logpdf we indeed get a correct estimate. But the projection still uses this term to [compute the gradient](https://github.com/ReactiveBayes/ExponentialFamilyProjection.jl/blob/3e110fcacecedbfac641b6a99ef58bf32dd51f75/src/strategies/control_variate.jl#L129). Which makes me think again that the problem is not in stability/instability but rather something more complex :/

**Comment by bvdmitri** [comment]
We still can merge this, maybe we would need it in the future, just saying. The tests are failing though

**Comment by ismailsenoz** [comment]
I can take a look at the failing tests after we merge logbasemeasure PR. And then we can merge perhaps.

**Comment by bvdmitri** [comment]
Looks like the tests are failing due to the changed API of `Aqua.jl`. They changed the kyword arguments in the new version

**Review by bvdmitri — APPROVED** [review]

**Pull request merged**
