### PR TITLE
Fix add wishart wishartfast prod

### PR DESCRIPTION
**Pull request by Nimrais**
This PR addresses two issues:

#192: Missing product definition between Wishart and WishartFast
#216: ProductOf{InverseWishart, InverseWishartFast} not dispatched correctly

Added product rules for:

1. Wishart × WishartFast
2. InverseWishart × InverseWishartFast

The implementation converts the standard distribution to its "Fast" variant before computing the product, since *Fast variants are optimized versions of the same distributions used for messages.

Note: The product between two standard Wishart distributions is postponed until we have a specific model requiring this functionality.

### CODE REVIEW

**Comment by wouterwln** [comment]
Looks like you beat me to it. Will this not break if `Wishart` or `InverseWishart` is on the right side instead of left? And can you add tests for `InverseWishart` too?

**Comment by Nimrais** [comment]
Ah hoped that you already have tests, yeah I will do.

**Comment by Nimrais** [comment]
> Will this not break if Wishart or InverseWishart is on the right side instead of left?

not it does not I have test for this. In bayes base we check if there is a rule if we will swap the arguments.

**Comment by wouterwln** [comment]
Perfect. Poke me if you're done, I will review and merge.

**Review by wouterwln — APPROVED** [review]

**Pull request merged**
